---
# User-specific OpenSSH setup
# ===========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Set up OpenSSH utility programs
  import_tasks: bin/main.yml

- name: Set up OpenSSH configuration files
  import_tasks: config/main.yml
