---
# User-specific Util setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy utility programs to binary directory
  copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - bin/*

- name: Create shortcuts to utility programs
  file:
    src: "{{ item.src }}"
    dest: "{{ bin_dir }}/{{ item.dest }}"
    state: link
  loop:
    - { src: 'file-backup', dest: 'fb' }
    - { src: 'file-path', dest: 'fp' }
    - { src: 'file-type', dest: 'ft' }
    - { src: 'file-view', dest: 'fv' }
