---
# User-specific GnuPG setup
# =========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"
    - "{{ gnupg_dir }}"

- name: Copy GnuPG configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ gnupg_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - config/*

