---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Git Revert Commands
  copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - command/revert/bin/git-u*

- name: Create shortcuts to Git Revert Commands
  file:
    src: "{{ item | basename }}"
    dest: "{{ bin_dir }}/\
           {{ item \
           | basename \
           | regex_replace('^git-u(.*)', '/gu\\1') }}"
    state: link
  with_fileglob:
    - command/revert/bin/git-u*
