---
# System-specific OpenSSH setup
# =============================
# Tim Friske <me@tifr.de>

- name: Manage state of OpenSSH host key
  community.crypto.openssh_keypair:
    type: "{{ item.algorithm }}"
    size: "{{ item.size_bits | default(omit) }}"
    path: "{{ item.path_prefix }}"
    state: >-
      {{
        item.state | default(
          'present'
            if item.version.supported <= openssh_sshd_version
              and (
              item.version.deprecated is not defined
              or not item.version.deprecated <= openssh_sshd_version
            )
            else 'absent'
        )
      }}
    regenerate: "{{ item.regenerate | default('fail') }}"
    comment: >-
      OpenSSH {{ item.algorithm | upper }} key
      of host {{ ansible_hostname }}

- name: Detect state of secret OpenSSH host key
  stat:
    path: "{{ item.path_prefix }}"
  register: openssh_key_secret_stat

- name: Adjust state of secret OpenSSH host key
  file:
    path: "{{ item.path_prefix }}"
    state: "{{ 'file' if openssh_key_secret_stat.stat.exists else 'absent' }}"
    mode: a=,u=r

- name: Detect state of public OpenSSH host key
  stat:
    path: "{{ item.path_prefix }}.pub"
  register: openssh_key_public_stat

- name: Adjust state of public OpenSSH host key
  file:
    path: "{{ item.path_prefix }}.pub"
    state: "{{ 'file' if openssh_key_public_stat.stat.exists else 'absent' }}"
    mode: a=r
