---
# System-specific OpenSSH setup
# =============================
# Tim Friske <me@tifr.de>

- name: Manage state of OpenSSH host key
  community.crypto.openssh_keypair:
    type: "{{ item.algorithm }}"
    size: "{{ item.size_bits | default(omit) }}"
    path: "{{ item.secret_key }}"
    state: >-
      {{
        item.state | default(
          'present'
            if item.supported_version <= sshd_version
              and (
              item.deprecated_version is not defined
              or not item.deprecated_version <= sshd_version
            )
            else 'absent'
        )
      }}
    regenerate: "{{ item.regenerate | default('fail') }}"
    comment: >-
      OpenSSH {{ item.algorithm | upper }} key
      of host {{ ansible_hostname }}
