---
# System-specific OpenSSH setup
# =============================
# Tim Friske <me@tifr.de>

- name: Lookup OpenSSH host key variables
  set_fact:
    openssh_host_key_algorithm: "{{ lookup('vars', 'openssh_host_key_' + item + '_algorithm') }}"
    openssh_host_key_size_bits: "{{ lookup('vars', 'openssh_host_key_' + item + '_size_bits') }}"
    openssh_host_key_version_supported: "{{ lookup('vars', 'openssh_host_key_' + item +  '_version_supported') }}"
    openssh_host_key_version_deprecated: "{{ lookup('vars', 'openssh_host_key_' + item +  '_version_deprecated') }}"
    openssh_host_key_state: "{{ lookup('vars', 'openssh_host_key_' + item + '_state') }}"
    openssh_host_key_regenerate: "{{ lookup('vars', 'openssh_host_key_' + item + '_regenerate') }}"
    openssh_host_key_path_prefix: "{{ lookup('vars', 'openssh_host_key_' + item + '_path_prefix') }}"
    openssh_host_key_secret_owner: "{{ lookup('vars', 'openssh_host_key_' + item + '_secret_owner') }}"
    openssh_host_key_secret_group: "{{ lookup('vars', 'openssh_host_key_' + item + '_secret_group') }}"
    openssh_host_key_secret_perms: "{{ lookup('vars', 'openssh_host_key_' + item + '_secret_perms') }}"
    openssh_host_key_public_owner: "{{ lookup('vars', 'openssh_host_key_' + item + '_public_owner') }}"
    openssh_host_key_public_group: "{{ lookup('vars', 'openssh_host_key_' + item + '_public_group') }}"
    openssh_host_key_public_perms: "{{ lookup('vars', 'openssh_host_key_' + item + '_public_perms') }}"

- name: Manage state of OpenSSH host key
  community.crypto.openssh_keypair:
    type: "{{ openssh_host_key_algorithm }}"
    size: "{{ openssh_host_key_size_bits | default(omit, true) }}"
    path: "{{ openssh_host_key_path_prefix }}"
    state: >-
      {{
        openssh_host_key_state | default(
          'present'
            if openssh_host_key_version_supported <= openssh_version
              and (
                openssh_host_key_version_deprecated | length == 0
                or not openssh_host_key_version_deprecated <= openssh_version
              )
            else 'absent', true
          )
      }}
    regenerate: "{{ openssh_host_key_regenerate | default('fail', true) }}"
    comment: >-
      OpenSSH {{ openssh_host_key_algorithm | upper }} key
      of host {{ ansible_hostname }}

- name: Detect state of secret OpenSSH host key
  stat:
    path: "{{ openssh_host_key_path_prefix }}"
  register: openssh_host_key_secret_stat

- name: Adjust state of secret OpenSSH host key
  file:
    path: "{{ openssh_host_key_path_prefix }}"
    owner: "{{ openssh_host_key_secret_owner }}"
    group: "{{ openssh_host_key_secret_group }}"
    mode: "{{ openssh_host_key_secret_perms }}"
    state: "{{ 'file' if openssh_host_key_secret_stat.stat.exists else 'absent' }}"

- name: Detect state of public OpenSSH host key
  stat:
    path: "{{ openssh_host_key_path_prefix }}.pub"
  register: openssh_host_key_public_stat

- name: Adjust state of public OpenSSH host key
  file:
    path: "{{ openssh_host_key_path_prefix }}.pub"
    owner: "{{ openssh_host_key_public_owner }}"
    group: "{{ openssh_host_key_public_group }}"
    mode: "{{ openssh_host_key_public_perms }}"
    state: "{{ 'file' if openssh_host_key_public_stat.stat.exists else 'absent' }}"
