---
# System-specific OpenSSH setup
# =============================
# Tim Friske <me@tifr.de>

- name: Get OpenSSH version
  command: ssh -V
  register: openssh_version_raw
  changed_when: false
  check_mode: false

- name: Parse OpenSSH version
  set_fact:
    openssh_version: >-
      {{
        openssh_version_raw.stderr
        | regex_replace('.*_([0-9]*.[0-9]).*', '\\1')
      }}

- name: Manage OpenSSH directories
  import_tasks: directory.yml

- name: Manage sysconfig file
  import_tasks: sysconfig.yml

- name: Manage moduli file
  import_tasks: moduli.yml

- name: Manage OpenSSH host keys
  include_tasks: key.yml
  loop: "{{ openssh_host_key_algorithms }}"
