---
# System-specific OpenSSH setup
# =============================
# Tim Friske <me@tifr.de>

- name: Get OpenSSH version
  command: ssh -V
  register: openssh_sshd_version_raw
  changed_when: false
  check_mode: false

- name: Parse OpenSSH version
  set_fact:
    openssh_sshd_version: >-
      {{
        openssh_sshd_version_raw.stderr
        | regex_replace('.*_([0-9]*.[0-9]).*', '\\1')
      }}

- name: Disable auto generation of OpenSSH host keys
  lineinfile:
    regexp: '^SSHD_AUTO_KEYGEN="yes"$'
    line: SSHD_AUTO_KEYGEN="no"
    path: /etc/sysconfig/ssh
    state: present

- name: Delete OpenSSH drop-in configuration directories
  file:
    path: "/etc/ssh/{{ item }}"
    state: absent
  loop:
    - ssh_config.d
    - sshd_config.d

- name: Create non-existing OpenSSH host keys
  include_tasks: key.yml
  loop:
    - "{{ openssh_key_dsa }}"
    - "{{ openssh_key_rsa }}"
    - "{{ openssh_key_ecdsa }}"
    - "{{ openssh_key_ed25519 }}"
