---
# System-specific OpenSSH setup
# =============================
# Tim Friske <me@tifr.de>

- name: Determine OpenSSH version
  import_tasks: version.yml

- name: Manage OpenSSH directories
  import_tasks: directory.yml

- name: Manage sysconfig file
  import_tasks: sysconfig.yml

- name: Manage moduli file
  import_tasks: moduli.yml

- name: Manage OpenSSH host keys
  include_tasks: key.yml
  loop: "{{ openssh_host_key_algorithms }}"
