---
# System-specific OpenSSH setup
# =============================
# Tim Friske <me@tifr.de>

- name: Get OpenSSH version
  command: ssh -V
  register: sshd_version_raw
  changed_when: false
  check_mode: false

- name: Parse OpenSSH version
  set_fact:
    sshd_version: >-
      {{
        sshd_version_raw.stderr
        | regex_replace('.*_([0-9]*.[0-9]).*', '\\1')
      }}

- name: Disable auto generation of OpenSSH host keys
  lineinfile:
    regexp: '^SSHD_AUTO_KEYGEN="yes"$'
    line: SSHD_AUTO_KEYGEN="no"
    path: /etc/sysconfig/ssh
    state: present
