---
# User-specific Tmux setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ user_dir }}"

- name: Copy Tmux configuration file
  copy:
    src: tmux.conf
    dest: "{{ user_dir }}/.tmux.conf"

- name: Set up binary directory with programs and scripts
  import_tasks: bin/main.yml

- name: Test if operating system is using Systemd
  find:
    patterns: systemctl
    paths: "{{ ansible_env.PATH.split(':') }}"
  register: systemctl

- name: Enable Tmux server via Systemd user units
  import_tasks: systemd/user/main.yml
  when: systemctl.matched > 0
