---
# User-specific Tmux setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ user_dir }}"

- name: Set up configuration files
  import_tasks: config/main.yml

- name: Set up programs and scripts
  import_tasks: bin/main.yml

- name: Check if operating system uses Systemd
  find:
    patterns: systemctl
    paths: "{{ ansible_env.PATH.split(':') }}"
  register: systemctl

- name: Set up Systemd units
  import_tasks: systemd/user/main.yml
  when: systemctl.matched > 0
