---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: fedora-31
    image: fedora:31
    dockerfile: Dockerfile.j2
    override_command: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible-test
verifier:
  name: ansible
