---
# User-specific Vim setup
# =======================
# Tim Friske <me@tifr.de>

# Vim main tasks
# --------------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ backup_dir }}"
    - "{{ swap_dir }}"
    - "{{ undo_dir }}"
    - "{{ vim_dir }}"

- name: Copy Vim configuration file
  copy:
    src: vim/vimrc
    dest: "{{ vim_dir }}/vimrc"
