---
# User-specific setup
# ===================
# Tim Friske <me@tifr.de>

# Site tasks
# ----------
- name: Setup of hosts with configuration files
  hosts: "{{ hosts_var }}"
  roles:

    # GNU Bash shell
    # --------------
    - role: bash
      tags:
        - bash
        - shell

    # Date program
    # ------------
    - role: date
      tags:
        - date

    # Fzf fuzzy finder
    # ----------------
    - role: fzf
      tags:
        - fzf
        - fuzzy
        - find
        - search

    # Git version control system
    # --------------------------
    - role: git
      tags:
        - git
        - vcs

    # GnuPG OpenPGP crypto suite
    # --------------------------
    - role: gnupg
      tags:
        - gnupg
        - gpg
        - openpgp

    # Kubernetes cluster software
    # ---------------------------
    - role: kubernetes
      tags:
        - kubernetes
        - cluster

    # Ls file and folder lister
    # -------------------------
    - role: ls
      tags:
        - ls
        - list
        - listing
        - coreutils

    # OpenSSH secure shell
    # --------------------
    - role: openssh
      tags:
        - openssh
        - ssh

    # GNU Readline library
    # --------------------
    - role: readline
      tags:
        - readline
        - inputrc

    # Tmux terminal multiplexer
    # -------------------------
    - role: tmux
      tags:
        - tmux
        - terminal
        - multiplexer

    # Utility scripts and programs
    # ----------------------------
    - role: util
      tags:
        - util
        - utilities

    # Vim Vi Improved text editor
    # ---------------------------
    - role: vim
      tags:
        - vim
        - text
        - editor

    # Coreutils Wc program
    # --------------------
    - role: wc
      tags:
        - wc
        - coreutils

    # Freedesktop.org config files
    # ----------------------------
    - role: xdg
      tags:
        - xdg
        - xdesktopgroup
        - freedesktop
