---
# Main Ansible playbook of user setup
# ===================================
# Tim Friske <me@tifr.de>

- name: Setup of hosts with configuration files
  hosts: "{{ hosts_var }}"
  roles:

    # GNU Bash shell
    # --------------
    - role: bash
      tags:
        - bash
        - shell

    # Git version control system
    # --------------------------
    - role: git
      tags:
        - git
        - vcs

    # GnuPG OpenPGP crypto suite
    # --------------------------
    - role: gnupg
      tags:
        - gnupg
        - gpg
        - openpgp

    # OpenSSH secure shell
    # --------------------
    - role: openssh
      tags:
        - openssh
        - ssh

    # GNU Readline library
    # --------------------
    - role: readline
      tags:
        - readline
        - inputrc

    # Tmux terminal multiplexer
    # -------------------------
    - role: tmux
      tags:
        - tmux
        - terminal
        - multiplexer

    # Utility scripts and programs
    # ----------------------------
    - role: util
      tags:
        - util
        - utilities

    # Vim Vi Improved text editor
    # ---------------------------
    - role: vim
      tags:
        - vim
        - text
        - editor

    # Freedesktop.org config files
    # ----------------------------
    - role: xdg
      tags:
        - xdg
        - xdesktopgroup
        - freedesktop
