---
# User-specific XDG setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ autostart_dir }}"

- name: Copy XDG autostart configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ autostart_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - autostart/*
