---
# User-specific Bash setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ rc_dir }}"

- name: Set up Bash aliases
  import_tasks: rc.d/alias/main.yml
