---
# User-specific Bash setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ drop_in_dir }}"

- name: Copy file with environment for Tar
  copy:
    src: login.d/drop-in/tar.bash
    dest: "{{ drop_in_dir }}/tar.bash"
