---
# System-specific OpenSSH setup
# =============================
# Tim Friske <me@tifr.de>
#
# Unless the _state_ property is of a key specified the absence or
# presence of it depends on since when the key algorithm is supported
# and/or deprecated (see _key.yml_ task file).
#
# Unless the _regenerate_ property of a key is specified this role fails
# to regenerate it if a key at that path already exists and exposes
# diverting properties (see _key.yml_ task file).

# OpenSSH directories
# -------------------

openssh_config_dir: /etc/ssh
openssh_config_dir_client: "{{ openssh_config_dir }}/ssh_config.d"
openssh_config_dir_daemon: "{{ openssh_config_dir }}/sshd_config.d"

# OpenSSH files
# -------------

openssh_sysconfig_file: /etc/sysconfig/ssh

# OpenSSH host key
# ----------------

openssh_host_key_algorithms: [dsa, rsa, ecdsa, ed25519]

# OpenSSH host key - DSA alogorithm
# ---------------------------------

openssh_host_key_dsa_algorithm: dsa
# size_bits is fixed (FIPS 186-2 Change Notice 1)
openssh_host_key_dsa_size_bits: 1024
openssh_host_key_dsa_version_supported: "2.2"
openssh_host_key_dsa_version_deprecated: "7.0"
openssh_host_key_dsa_state: null
openssh_host_key_dsa_regenerate: null
openssh_host_key_dsa_path_prefix: "{{ openssh_config_dir }}/ssh_host_dsa_key"
openssh_host_key_dsa_secret_owner: root
openssh_host_key_dsa_secret_group: root
openssh_host_key_dsa_secret_perms: u=r,go=
openssh_host_key_dsa_public_owner: root
openssh_host_key_dsa_public_group: root
openssh_host_key_dsa_public_perms: ugo=r

# OpenSSH host key - RSA algorithm
# --------------------------------

openssh_host_key_rsa_algorithm: rsa
# size_bits is increased to 4096 bits for security
openssh_host_key_rsa_size_bits: 4096
openssh_host_key_rsa_version_supported: "5.3"
openssh_host_key_rsa_version_deprecated: null
openssh_host_key_rsa_state: null
openssh_host_key_rsa_regenerate: null
openssh_host_key_rsa_path_prefix: "{{ openssh_config_dir }}/ssh_host_rsa_key"
openssh_host_key_rsa_secret_owner: root
openssh_host_key_rsa_secret_group: root
openssh_host_key_rsa_secret_perms: u=r,go=
openssh_host_key_rsa_public_owner: root
openssh_host_key_rsa_public_group: root
openssh_host_key_rsa_public_perms: ugo=r

# OpenSSH host key - ECDSA algorithm
# ----------------------------------

openssh_host_key_ecdsa_algorithm: ecdsa
# size_bits is increased to 521 bits for security
openssh_host_key_ecdsa_size_bits: 521
openssh_host_key_ecdsa_version_supported: "6.0"
openssh_host_key_ecdsa_version_deprecated: null
openssh_host_key_ecdsa_state: null
openssh_host_key_ecdsa_regenerate: null
openssh_host_key_ecdsa_path_prefix: "{{ openssh_config_dir }}/ssh_host_ecdsa_key"
openssh_host_key_ecdsa_secret_owner: root
openssh_host_key_ecdsa_secret_group: root
openssh_host_key_ecdsa_secret_perms: u=r,go=
openssh_host_key_ecdsa_public_owner: root
openssh_host_key_ecdsa_public_group: root
openssh_host_key_ecdsa_public_perms: ugo=r

# OpenSSH host key - ED25519 algorithm
# ------------------------------------

openssh_host_key_ed25519_algorithm: ed25519
# size_bits is fixed
openssh_host_key_ed25519_size_bits: null
openssh_host_key_ed25519_version_supported: "6.3"
openssh_host_key_ed25519_version_deprecated: null
openssh_host_key_ed25519_state: null
openssh_host_key_ed25519_regenerate: null
openssh_host_key_ed25519_path_prefix: "{{ openssh_config_dir }}/ssh_host_ed25519_key"
openssh_host_key_ed25519_secret_owner: root
openssh_host_key_ed25519_secret_group: root
openssh_host_key_ed25519_secret_perms: u=r,go=
openssh_host_key_ed25519_public_owner: root
openssh_host_key_ed25519_public_group: root
openssh_host_key_ed25519_public_perms: ugo=r
