---
# User-specific GnuPG setup
# =========================
# Tim Friske <me@tifr.de>

# Copying of Systemd user unit files
# ----------------------------------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ systemd_user_dir }}"

- name: Copy GnuPG Dirmngr service unit file
  copy:
    src: systemd/user/dirmngr.service
    dest: "{{ systemd_user_dir }}/dirmngr.service"

- name: Copy GnuPG Dirmngr socket unit file
  copy:
    src: systemd/user/dirmngr.socket
    dest: "{{ systemd_user_dir }}/dirmngr.socket"

- name: Copy GnuPG GPG agent browser socket unit file
  copy:
    src: systemd/user/gpg-agent-browser.socket
    dest: "{{ systemd_user_dir }}/gpg-agent-browser.socket"

- name: Copy GnuPG GPG agent extra socket unit file
  copy:
    src: systemd/user/gpg-agent-extra.socket
    dest: "{{ systemd_user_dir }}/gpg-agent-extra.socket"

- name: Copy GnuPG GPG agent service unit file
  copy:
    src: systemd/user/gpg-agent.service
    dest: "{{ systemd_user_dir }}/gpg-agent.service"

- name: Copy GnuPG GPG agent socket unit file
  copy:
    src: systemd/user/gpg-agent.socket
    dest: "{{ systemd_user_dir }}/gpg-agent.socket"

- name: Copy GnuPG GPG agent SSH socket unit file
  copy:
    src: systemd/user/gpg-agent-ssh.socket
    dest: "{{ systemd_user_dir }}/gpg-agent-ssh.socket"
