---
# Enabling of GnuPG's Systemd user unit files
# ===========================================
# Tim Friske <me@tifr.de>

- name: Start GnuPG's Dirmngr on-demand
  systemd:
    unit: dirmngr.socket
    scope: user
    enabled: yes
    state: started
    no_block: yes

- name: Start GnuPG's Gpg-agent on-demand
  systemd:
    unit: gpg-agent.socket
    scope: user
    enabled: yes
    state: started
    no_block: yes

- name: Start GnuPG's Gpg-agent with browser support daemon on-demand
  systemd:
    unit: gpg-agent-browser.socket
    scope: user
    enabled: yes
    state: started
    no_block: yes

- name: Start GnuPG's Gpg-agent with extra support daemon on-demand
  systemd:
    unit: gpg-agent-extra.socket
    scope: user
    enabled: yes
    state: started
    no_block: yes

- name: Start GnuPG's Gpg-agent with SSH support on-demand
  systemd:
    unit: gpg-agent-ssh.socket
    scope: user
    enabled: yes
    state: started
    no_block: yes
