---
# User-specific GnuPG setup
# =========================
# Tim Friske <me@tifr.de>

# Systemd user unit setup
# -----------------------
- name: Copy GnuPG's Systemd user unit files
  import_tasks: copy.yml

- name: Enable GnuPG's Systemd user unit files
  import_tasks: enable.yml
