---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ git_dir }}"

- name: Copy Git Global configuration file
  copy:
    src: global.conf
    dest: "{{ git_dir }}/global.conf"
  tags: git-config

- name: Link Git Config file to Global configuration file
  file:
    src: global.conf
    dest: "{{ git_dir }}/config"
    state: link
  tags: git-config

- name: Set up binary directory with Git commands
  import_tasks: bin/main.yml
  tags: git-command

- name: Set up binary directory with Git Add commands
  import_tasks: command/add/bin/main.yml
  tags: git-add

- name: Set up binary directory with Git Bisect commands
  import_tasks: command/bisect/bin/main.yml
  tags: git-bisect

- name: Set up binary directory with Git Branch commands
  import_tasks: command/branch/bin/main.yml
  tags: git-branch

- name: Set up binary directory with Git Checkout commands
  import_tasks: command/checkout/bin/main.yml
  tags: git-checkout

- name: Set up binary directory with Git Cherry commands
  import_tasks: command/cherry/bin/main.yml
  tags: git-cherry

- name: Set up binary directory with Git Cherry-pick commands
  import_tasks: command/cherry-pick/bin/main.yml
  tags: git-cherry-pick

- name: Set up binary directory with Git Commit commands
  import_tasks: command/commit/bin/main.yml
  tags: git-commit

- name: Set up binary directory with Git Diff commands
  import_tasks: command/diff/bin/main.yml
  tags: git-diff

- name: Set up binary directory with Git Edit commands
  import_tasks: command/edit/bin/main.yml
  tags: git-edit

- name: Set up binary directory with Git Fetch commands
  import_tasks: command/fetch/bin/main.yml
  tags: git-fetch

- name: Set up binary directory with Git Help commands
  import_tasks: command/help/bin/main.yml
  tags: git-help

- name: Set up binary directory with Git Log commands
  import_tasks: command/log/bin/main.yml
  tags: git-log

- name: Set up binary directory with Git Location commands
  import_tasks: command/location/bin/main.yml
  tags: git-location

- name: Set up binary directory with Git Merge commands
  import_tasks: command/merge/bin/main.yml
  tags: git-merge

- name: Set up binary directory with Git Misc commands
  import_tasks: command/misc/bin/main.yml
  tags: git-misc

- name: Set up binary directory with Git Rebase commands
  import_tasks: command/rebase/bin/main.yml
  tags: git-rebase

- name: Set up binary directory with Git Reset commands
  import_tasks: command/reset/bin/main.yml
  tags: git-reset

- name: Set up binary directory with Git Revert commands
  import_tasks: command/revert/bin/main.yml
  tags: git-revert

- name: Set up binary directory with Git Show commands
  import_tasks: command/show/bin/main.yml
  tags: git-show

- name: Set up binary directory with Git Stash commands
  import_tasks: command/stash/bin/main.yml
  tags: git-stash

- name: Set up binary directory with Git Status commands
  import_tasks: command/status/bin/main.yml
  tags: git-status

- name: Set up binary directory with Git Tag commands
  import_tasks: command/tag/bin/main.yml
  tags: git-tag

- name: Set up Git Global configuration directory
  import_tasks: global.d/main.yml
  tags: git-config
