---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ git_dir }}"

- name: Copy Git Global configuration file
  copy:
    src: global.conf
    dest: "{{ git_dir }}/global.conf"

- name: Link Git Config file to Global configuration file
  file:
    src: global.conf
    dest: "{{ git_dir }}/config"
    state: link

- name: Set up Git Global configuration directory
  import_tasks: global.d/main.yml
