---
# User-specific Fzf setup
# =======================
# Tim Friske <me@tifr.de>

- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Fzf Files utility Bash script
  copy:
    src: bin/fzf-files.bash
    dest: "{{ bin_dir }}/fzf-files.bash"

- name: Copy Fzf Find utility program
  copy:
    src: bin/fzf-find
    dest: "{{ bin_dir }}/fzf-find"
    mode: a+x

- name: Copy Fzf Folders utility Bash script
  copy:
    src: bin/fzf-folders.bash
    dest: "{{ bin_dir }}/fzf-folders.bash"

- name: Copy Fzf Git Branch utility program
  copy:
    src: bin/fzf-git-branch
    dest: "{{ bin_dir }}/fzf-git-branch"
    mode: a+x

- name: Copy Fzf Git Branch Insert utility Bash script
  copy:
    src: bin/fzf-git-branch-insert.bash
    dest: "{{ bin_dir }}/fzf-git-branch-insert.bash"

- name: Copy Fzf Git Tag utility program
  copy:
    src: bin/fzf-git-tag
    dest: "{{ bin_dir }}/fzf-git-tag"
    mode: a+x

- name: Copy Fzf Git Tag Insert utility Bash script
  copy:
    src: bin/fzf-git-tag-insert.bash
    dest: "{{ bin_dir }}/fzf-git-tag-insert.bash"

- name: Copy Fzf history utility program
  copy:
    src: bin/fzf-history
    dest: "{{ bin_dir }}/fzf-history"
    mode: a+x

- name: Copy Fzf Insert utility Bash script
  copy:
    src: bin/fzf-insert.bash
    dest: "{{ bin_dir }}/fzf-insert.bash"

- name: Copy Fzf Jobs utility program
  copy:
    src: bin/fzf-jobs
    dest: "{{ bin_dir }}/fzf-jobs"
    mode: a+x

- name: Copy Fzf pick utility program
  copy:
    src: bin/fzf-pick
    dest: "{{ bin_dir }}/fzf-pick"
    mode: a+x

- name: Copy Fzf Quote utility program
  copy:
    src: bin/fzf-quote
    dest: "{{ bin_dir }}/fzf-quote"
    mode: a+x

- name: Copy Fzf Sort utility program
  copy:
    src: bin/fzf-sort
    dest: "{{ bin_dir }}/fzf-sort"
    mode: a+x
