---
# User-specific Fzf setup
# =======================
# Tim Friske <me@tifr.de>

- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Fzf programs
  copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - bin/*

- name: Check if Fd utility program is in PATH
  shell: "which fd"
  register: fd_in_path
  ignore_errors: true
  changed_when: false

- name: Link Fzf Finder to Fzf Fd utility program
  file:
    src: "{{ bin_dir }}/fzf-fd"
    dest: "{{ bin_dir }}/fzf-finder"
    state: link
  when: fd_in_path.rc == 0

- name: Link Fzf Finder to Fzf Find utility program
  file:
    src: "{{ bin_dir }}/fzf-find"
    dest: "{{ bin_dir }}/fzf-finder"
    state: link
  when: fd_in_path.rc != 0
