---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Git Location command
  copy:
    src: command/location/bin/git-location
    dest: "{{ bin_dir }}/git-location"
    mode: preserve
