---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Git Add Commands
  copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: a+x
  with_fileglob:
    - command/add/bin/git-a*

- name: Create shortcuts to Git Add Commands
  file:
    src: "{{ item | basename }}"
    dest: "{{ bin_dir }}/\
           {{ item \
           | basename \
           | regex_replace('^git-a(.*)', '/ga\\1') }}"
    state: link
  with_fileglob:
    - command/add/bin/git-a*
