---
# Main Ansible playbook of user specific Bash setup
# =================================================
# Tim Friske <me@tifr.de>

- name: Copy Bash startup file for login shells
  copy:
    src: bash_login
    dest: "{{ user_dir }}/.bash_login"

- name: Copy Bash startup file for interactive shells
  copy:
    src: bashrc
    dest: "{{ user_dir }}/.bashrc"
