---
# User-specific Bash setup
# ========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ user_dir }}"

- name: Copy Bash startup file for login shells
  copy:
    src: login
    dest: "{{ user_dir }}/.bash_login"

- name: Copy Bash startup file for interactive shells
  copy:
    src: rc
    dest: "{{ user_dir }}/.bashrc"
