---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# Main variables
# --------------
os_name: "{{ ansible_distribution }}"
os_name_id: "{{ os_name | lower | replace(' ', '-') }}"

os_version: "{{ ansible_distribution_version }}"
os_version_id: "{{ os_version | lower | replace('.', '-') }}"
