---
# System-wide installation
# ========================
# Tim Friske <me@tifr.de>

# Main variables
# --------------
os_name: "{{ ansible_distribution }}"
os_name_id: "{{ os_name | lower | replace(' ', '-') }}"
