---
# User-specific GnuPG setup
# =========================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"
    - "{{ gnupg_dir }}"

- name: Copy GnuPG backup utility program
  copy:
    src: gpg-backup
    dest: "{{ bin_dir }}/gpg-backup"
    mode: preserve

- name: Copy GnuPG user key generation utility program
  copy:
    src: gpg-gen-key-for-user
    dest: "{{ bin_dir }}/gpg-gen-key-for-user"
    mode: preserve

- name: Test if operating system is using Systemd
  find:
    patterns: systemctl
    paths: "{{ ansible_env.PATH.split(':') }}"
  register: systemctl

- name: Enable GnuPG daemons via Systemd user units
  import_tasks: systemd/user/main.yml
  when: systemctl.matched > 0

- name: Set up GnuPG configuration files
  import_tasks: config/main.yml
