---
# User-specific Git setup
# =======================
# Tim Friske <me@tifr.de>

# Main tasks
# ----------
- name: Make target directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ bin_dir }}"

- name: Copy Git Cherry-pick Commands
  copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - command/cherry-pick/bin/git-xcp*

- name: Create shortcuts to Git Cherry-pick Commands
  file:
    src: "{{ item | basename }}"
    dest: "{{ bin_dir }}/\
           {{ item \
           | basename \
           | regex_replace('^git-xcp(.*)', '/gxcp\\1') }}"
    state: link
  with_fileglob:
    - command/cherry-pick/bin/git-xcp*
