---
# Main Ansible variables of user specific Xdg setup
# =================================================
# Tim Friske <me@tifr.de>

user_dir: "{{ ansible_env.HOME }}"

config_dir: "{{ user_dir }}/.config"

autostart_dir: "${{ config_dir }}/autostart"
