---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-18-04
    image: ubuntu:18.04
    dockerfile: Dockerfile.j2
    override_command: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible-test
verifier:
  name: ansible
