---
# Amazon AWS EKS Cluster CloudFormation template
# ==============================================
# Tim Friske <me@tifr.de>
#
# Amazon License
# --------------
# Copyright (c) 2018 Amazon.com, Inc. or its affiliates.  All rights
# reserved.
#
# AWS CloudFormation template to create the resources pertaining to the
# control plane of the EKS cluster.

AWSTemplateFormatVersion: 2010-09-09
