---
# Amazon AWS EKS VPC Network CloudFormation template
# ==================================================
# Tim Friske <me@tifr.de>
#
# Amazon License
# --------------
# Copyright (c) 2018 Amazon.com, Inc. or its affiliates.  All rights
# reserved.
#
# This file originates from the
# https://amazon-eks.s3-us-west-2.amazonaws.com/[Amazon EKS S3 bucket].
# Its original version can be found under
# `cloudformation/2019-02-11/amazon-eks-vpc-sample.yaml`.
#
# AWS CloudFormation template to create the resources pertaining to the
# VPC network of the EKS cluster.

AWSTemplateFormatVersion: 2010-09-09

Description: >-
  The Amazon AWS EKS VPC network configuration.

Metadata:

Parameters:

  VpcNetworkCidrBlock:
    Type: String
    Default: 192.168.0.0/16
    AllowedPattern:
      "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}\
      ([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    Description: >-
      The CIDR block for the VPC network. This should be a valid private
      (RFC 1918) CIDR range.

Resources:

  Network:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcNetworkCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: ${AWS::StackName}-internet-gateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref Network
