---
# Amazon AWS EKS Workers CloudFormation template
# ==============================================
# Tim Friske <me@tifr.de>
#
# Amazon License
# --------------
# Copyright (c) 2018 Amazon.com, Inc. or its affiliates.  All rights
# reserved.
#
# This file originates from the
# https://amazon-eks.s3-us-west-2.amazonaws.com/[Amazon EKS S3 bucket]
# GitHub repository.  Its original version can be found under
# `/cloudformation/2019-02-11/amazon-eks-nodegroup.yaml`.
#
# AWS CloudFormation template to create the resources pertaining to the
# worker nodes of the EKS cluster.

AWSTemplateFormatVersion: 2010-09-09

Description: >-
  The Amazon AWS EKS worker nodes configuration.

Parameters:

  NodeRoleName:
    Type: String
    Default: eks-node-instance-role
    AllowedPattern: "^\\S+$"
    Description: >-
      Name of an existing IAM role that shall be assigned to the worker
      nodes such that they can register with the master nodes of the
      control plane.

Resources:

  NodeProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref NodeRoleName
